export interface Category {
  id: string;
  code: string;
  name: string;
  icon: string;
}

export interface Item {
  id: string;
  code: string;
  docNo: string;
  name: string;
}

export type AccountGroup = "資產" | "成本" | "費用";

export interface Account {
  code: string;
  name: string;
  group: AccountGroup;
}

export const CATEGORIES: Category[] = [
  { id: "313e528b", code: "TEMPORARY_WORKS",                    name: "假設工程",       icon: "Construction" },
  { id: "f9a3a385", code: "FOUNDATION_WORKS",                   name: "基礎工程",       icon: "Layers" },
  { id: "10aec29f", code: "STRUCTURAL_WORKS",                   name: "結構體工程",     icon: "Building2" },
  { id: "1f44324a", code: "FINISHING_WORKS",                    name: "裝修工程",       icon: "PaintRoller" },
  { id: "be972ca8", code: "DOOR_AND_WINDOW_WORKS",              name: "門窗工程",       icon: "DoorOpen" },
  { id: "8ad2e2a4", code: "ELEVATOR_AND_PARKING_EQUIPMENT",     name: "電梯及停車設備", icon: "ArrowUpDown" },
  { id: "1585ae96", code: "WATERPROOFING_AND_INSULATION_WORKS", name: "防水隔熱工程",   icon: "Droplets" },
  { id: "56dc20ee", code: "METAL_WORKS",                        name: "金屬構件",       icon: "Wrench" },
  { id: "93865b72", code: "ENGINEERING_MATERIALS",              name: "工程材料",       icon: "Package" },
  { id: "26c24f2c", code: "MISCELLANEOUS_WORKS",                name: "雜項工程",       icon: "Boxes" },
  { id: "524970c5", code: "PUBLIC_AND_PERIPHERAL_WORKS",        name: "公共及週邊工程", icon: "Trees" },
  { id: "157c8825", code: "MECHANICAL_AND_ELECTRICAL_WORKS",    name: "機電工程",       icon: "Zap" },
];

const RAW_ITEMS: Record<string, { docNo: string; name: string }[]> = {
  "313e528b": [
    { docNo: "1",  name: "工務所設置費" },
    { docNo: "2",  name: "安全圍籬" },
    { docNo: "3",  name: "安全衛生設施" },
    { docNo: "4",  name: "活動廁所" },
    { docNo: "5",  name: "鷹架工程" },
    { docNo: "6",  name: "塔式吊車" },
    { docNo: "7",  name: "施工電梯" },
    { docNo: "8",  name: "垃圾管道(直管)" },
    { docNo: "9",  name: "電梯機道(活動帆布)" },
    { docNo: "10", name: "垃圾管道環保室" },
    { docNo: "11", name: "防墜安全措施" },
    { docNo: "12", name: "工地臨時水電" },
    { docNo: "13", name: "地質鑽探" },
    { docNo: "14", name: "鄰房鑑定工程" },
  ],
  "f9a3a385": [
    { docNo: "1", name: "舊建物拆除" },
    { docNo: "2", name: "連續壁工程" },
    { docNo: "3", name: "地下室安全措施" },
    { docNo: "4", name: "土方工程" },
    { docNo: "5", name: "地下室監測系統" },
  ],
  "10aec29f": [
    { docNo: "1", name: "模板工程" },
    { docNo: "2", name: "鋼筋綁紮工程" },
    { docNo: "3", name: "鋼筋成型加工費用" },
    { docNo: "4", name: "混凝土澆置導築" },
    { docNo: "5", name: "鋼筋續接器" },
    { docNo: "6", name: "鋼筋材料" },
    { docNo: "7", name: "混凝土材料" },
  ],
  "1f44324a": [
    { docNo: "1",  name: "室內隔間工程" },
    { docNo: "2",  name: "泥作工程" },
    { docNo: "3",  name: "石材工程" },
    { docNo: "4",  name: "油漆工程" },
    { docNo: "5",  name: "PVC天花板" },
    { docNo: "6",  name: "暗架防火天花板" },
    { docNo: "7",  name: "櫸木扶手" },
    { docNo: "8",  name: "整體粉光類" },
    { docNo: "9",  name: "廚具設備" },
    { docNo: "10", name: "木作工程" },
    { docNo: "11", name: "家具" },
    { docNo: "12", name: "飾品" },
    { docNo: "13", name: "健身器材" },
    { docNo: "14", name: "兒童遊具" },
    { docNo: "15", name: "窗簾" },
    { docNo: "16", name: "電器" },
    { docNo: "17", name: "植栽工程" },
    { docNo: "18", name: "塑木工程" },
  ],
  "be972ca8": [
    { docNo: "1", name: "木門類" },
    { docNo: "2", name: "塑鋼門" },
    { docNo: "3", name: "硫化銅門、防火門工程" },
    { docNo: "4", name: "鐵捲門工程" },
    { docNo: "5", name: "鋁門窗工程(含冷氣隔柵)" },
    { docNo: "6", name: "淋浴拉門" },
    { docNo: "7", name: "玻璃工程" },
    { docNo: "8", name: "自動排煙窗設備安裝工程" },
  ],
  "8ad2e2a4": [
    { docNo: "1", name: "電梯" },
    { docNo: "2", name: "機械停車設備" },
  ],
  "1585ae96": [
    { docNo: "1", name: "嵌縫工程" },
    { docNo: "2", name: "PU防水工程" },
    { docNo: "3", name: "矽利康工程" },
    { docNo: "4", name: "地下室防水粉刷工程" },
    { docNo: "5", name: "防水工程" },
    { docNo: "6", name: "伸縮縫工程" },
  ],
  "56dc20ee": [
    { docNo: "1",  name: "外牆包版" },
    { docNo: "2",  name: "陽台欄杆" },
    { docNo: "3",  name: "陽台格柵(含外牆及夾層格柵)" },
    { docNo: "4",  name: "屋頂鐵件" },
    { docNo: "5",  name: "地下室人孔鑄鐵蓋" },
    { docNo: "6",  name: "車道截水溝蓋" },
    { docNo: "7",  name: "水箱爬梯(內外)" },
    { docNo: "8",  name: "不銹鋼水箱蓋" },
    { docNo: "9",  name: "自來水總表蓋_不銹鋼" },
    { docNo: "10", name: "加壓馬達門片" },
    { docNo: "11", name: "1F放流管檢修口蓋" },
    { docNo: "12", name: "中庭及屋頂水溝蓋" },
    { docNo: "13", name: "出入口雨遮工程" },
    { docNo: "14", name: "不銹鋼曬被架" },
    { docNo: "15", name: "外牆發光字體(含格柵)" },
    { docNo: "16", name: "地下室停車告示牌" },
    { docNo: "17", name: "屋頂外觀造型燈牆" },
    { docNo: "18", name: "複式壁烤漆浪板" },
    { docNo: "19", name: "店鋪招牌" },
    { docNo: "20", name: "周邊圍牆鐵件" },
    { docNo: "21", name: "車道防水閘門" },
    { docNo: "22", name: "車道邊及中庭圍牆鐵件(環保室)" },
    { docNo: "23", name: "瓦斯遮斷閥鐵件" },
    { docNo: "24", name: "殘障坡道、車道欄杆h:75" },
    { docNo: "25", name: "伸縮曬衣架(含店鋪)" },
    { docNo: "26", name: "停車場欄杆H=65cm" },
    { docNo: "27", name: "室內鐵梯" },
    { docNo: "28", name: "車道限高標示包版(含電燈及燈座)" },
    { docNo: "29", name: "驗收用扶手" },
    { docNo: "30", name: "大樓地址門牌號碼安裝" },
    { docNo: "31", name: "不鏽鋼排水槽" },
    { docNo: "32", name: "鐵件工程(舊系統)" },
  ],
  "93865b72": [
    { docNo: "1",  name: "水泥" },
    { docNo: "2",  name: "紅磚" },
    { docNo: "3",  name: "砂" },
    { docNo: "4",  name: "碎石級配" },
    { docNo: "5",  name: "室內地磚" },
    { docNo: "6",  name: "室內拼花磁磚" },
    { docNo: "7",  name: "普浴室壁磚" },
    { docNo: "8",  name: "普浴室地磚" },
    { docNo: "9",  name: "陽台地磚" },
    { docNo: "10", name: "RF屋面壓頂磚" },
    { docNo: "11", name: "主浴室地磚" },
    { docNo: "12", name: "主浴室壁磚" },
    { docNo: "13", name: "普浴腰帶磚" },
    { docNo: "14", name: "廚房腰帶磚" },
    { docNo: "15", name: "工作陽台壁磚" },
    { docNo: "16", name: "廚房壁磚" },
    { docNo: "17", name: "雜項磁磚" },
    { docNo: "18", name: "前陽台地磚" },
    { docNo: "19", name: "工作陽台地磚" },
    { docNo: "20", name: "浴室門檻" },
    { docNo: "21", name: "大門門檻" },
    { docNo: "22", name: "粘著劑" },
    { docNo: "23", name: "填縫劑" },
    { docNo: "24", name: "清潔劑" },
    { docNo: "25", name: "車道止滑磚" },
    { docNo: "26", name: "水箱磁磚" },
    { docNo: "27", name: "電梯壁磚" },
    { docNo: "28", name: "電梯地磚" },
    { docNo: "29", name: "騎樓地磚" },
    { docNo: "30", name: "屋頂及露台地磚" },
    { docNo: "31", name: "樓梯石英止滑地磚" },
    { docNo: "32", name: "抿石子材料" },
    { docNo: "33", name: "抿石子粉" },
    { docNo: "34", name: "外牆磚" },
    { docNo: "35", name: "水泥磚" },
    { docNo: "36", name: "玻璃磚" },
    { docNo: "37", name: "白水泥" },
    { docNo: "38", name: "采麗泥" },
    { docNo: "39", name: "住戶門牌" },
    { docNo: "40", name: "店鋪地址門牌" },
    { docNo: "41", name: "陶板" },
    { docNo: "42", name: "主浴主牆面磁磚" },
    { docNo: "43", name: "雜項材料" },
    { docNo: "44", name: "門框保護塑膠板" },
    { docNo: "46", name: "ABS水溝蓋" },
  ],
  "26c24f2c": [
    { docNo: "1", name: "測量放樣" },
    { docNo: "2", name: "清潔工程" },
    { docNo: "3", name: "假設拆除" },
    { docNo: "4", name: "交通維持" },
    { docNo: "5", name: "環境保護措施" },
    { docNo: "6", name: "完工驗收清理" },
  ],
  "524970c5": [
    { docNo: "1", name: "道路工程" },
    { docNo: "2", name: "排水工程" },
    { docNo: "3", name: "景觀工程" },
    { docNo: "4", name: "圍牆工程" },
    { docNo: "5", name: "標誌標線" },
    { docNo: "6", name: "人行道鋪面" },
  ],
  "157c8825": [
    { docNo: "1", name: "給排水衛生設備" },
    { docNo: "2", name: "電氣工程" },
    { docNo: "3", name: "消防工程" },
    { docNo: "4", name: "空調工程" },
    { docNo: "5", name: "弱電及通訊工程" },
    { docNo: "6", name: "瓦斯工程" },
  ],
};

export const ITEMS_BY_CAT: Record<string, Item[]> = Object.fromEntries(
  Object.entries(RAW_ITEMS).map(([catId, raw]) => [
    catId,
    raw
      .slice()
      .sort((a, b) => parseFloat(a.docNo) - parseFloat(b.docNo))
      .map((it, i) => ({
        id: `${catId}-${it.docNo}`,
        code: `${catId}_${i}`,
        docNo: it.docNo,
        name: it.name,
      })),
  ])
);

export const ACCOUNTS: Account[] = [
  { code: "1501", name: "在建工程",              group: "資產" },
  { code: "1502", name: "機器設備",              group: "資產" },
  { code: "1601", name: "預付工程款",            group: "資產" },
  { code: "1602", name: "待攤費用",              group: "資產" },
  { code: "5401", name: "工程施工-合約成本",      group: "成本" },
  { code: "5402", name: "直接材料-鋼筋",          group: "成本" },
  { code: "5403", name: "直接材料-混凝土",        group: "成本" },
  { code: "5404", name: "直接材料-模板",          group: "成本" },
  { code: "5405", name: "直接材料-磁磚石材",      group: "成本" },
  { code: "5411", name: "直接人工-結構",          group: "成本" },
  { code: "5412", name: "直接人工-裝修",          group: "成本" },
  { code: "5421", name: "假設工程費",            group: "成本" },
  { code: "5422", name: "鷹架及安全設施",         group: "成本" },
  { code: "5423", name: "機具租賃-塔吊/施工電梯", group: "成本" },
  { code: "5431", name: "防水隔熱工程",           group: "成本" },
  { code: "5432", name: "門窗工程",              group: "成本" },
  { code: "5433", name: "泥作工程",              group: "成本" },
  { code: "5434", name: "油漆工程",              group: "成本" },
  { code: "5435", name: "金屬構件工程",           group: "成本" },
  { code: "5436", name: "機電工程-給排水電",       group: "成本" },
  { code: "5437", name: "機電工程-消防",          group: "成本" },
  { code: "5438", name: "機電工程-空調",          group: "成本" },
  { code: "5439", name: "電梯及停車設備",         group: "成本" },
  { code: "5441", name: "景觀植栽工程",           group: "成本" },
  { code: "5442", name: "公共設施工程",           group: "成本" },
  { code: "5451", name: "工程雜費",              group: "成本" },
  { code: "5452", name: "廢棄物清運費",           group: "成本" },
  { code: "5461", name: "試驗檢測費",            group: "成本" },
  { code: "5462", name: "鑑定及監測費",           group: "成本" },
  { code: "5471", name: "設計監造費",            group: "成本" },
  { code: "5481", name: "工地管理費",            group: "成本" },
  { code: "6101", name: "薪資支出",              group: "費用" },
  { code: "6102", name: "租金支出",              group: "費用" },
  { code: "6201", name: "保險費",                group: "費用" },
  { code: "6202", name: "稅捐",                  group: "費用" },
  { code: "6203", name: "修繕維護費",            group: "費用" },
];

export const ACCOUNT_GROUPS: AccountGroup[] = ["資產", "成本", "費用"];
